name: Publish to PyPi

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Publish to TestPyPi
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/garrett-streamlit-auth0

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clean prep area
        run: rm -fr dist/*

      - name: Build front end
        run: cd auth0_component/frontend/ && npm run ci

      - name: Build Component
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Tag main
        if: github.ref == 'refs/heads/main'
        run: /
          set -e
          NEW_TAG=`python setup.py --version`
          git config user.name 'Tag Bot'
          git config user.email 'garrett-streamlit-auth0@users.noreply.github.com'
          git tag -a ${NEW_TAG} -m "${NEW_TAG}" -f $GITHUB_SHA
          git push origin ${NEW_TAG}

      - name: Add Version to PR
        if: github.event_name == 'pull_request'
        run: |
          set -e
          NEW_TAG=`python setup.py --version`
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            ${{ github.event.pull_request.comments_url }} \
            -d '{"body":"Version: $NEW_TAG"}'
